[env.development]
WORKING_DIR = { script = ["pwd"] }
PULSO_VERSION = { script = ["cargo pkgid | cut -d '#' -f 2"] }
RUST_BACKTRACE = 1
RUST_LOG = "debug"

[config]
skip_core_tasks = true

[tasks.setcap]
command = "sudo"
args = ["setcap", "cap_net_raw=eip", "${WORKING_DIR}/target/debug/pulso"]

[tasks.build]
command = "cargo"
args = ["build", "--features", "immediate_mode"]

[tasks.test]
env = { "RUST_LOG" = "trace", "RUST_TEST_THREADS" = "1", "PULSO_SECRET" = "secret" }
command = "cargo"
args = ["test", "--features", "immediate_mode", "${@}"]
dependencies = ["build", "setcap"]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]
dependencies = ["build", "setcap"]

[tasks.release-build]
command = "cross"
args = ["build", "--target", "x86_64-unknown-linux-musl", "--release"]

[tasks.release-tar]
command = "tar"
args = [
  "-czvf",
  "releases/x86_64-unknown-linux-musl/pulso_${PULSO_VERSION}.tar.gz",
  "--directory=target/x86_64-unknown-linux-musl/release",
  "pulso"
]

[tasks.release]
dependencies = ["release-build", "release-tar"]
