[env.development]
WORKING_DIR = { script = ["pwd"] }
RUST_BACKTRACE = 1
RUST_LOG = "debug"

[tasks.setcap]
command = "sudo"
args = ["setcap", "cap_net_raw,cap_net_admin=eip", "${WORKING_DIR}/target/debug/pulso"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
env = { "RUST_LOG" = "trace", "RUST_TEST_THREADS" = "1", "PULSO_SECRET" = "secret" }
command = "cargo"
args = ["test", "${@}"]
dependencies = ["build", "setcap"]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]
dependencies = ["build", "setcap"]
