[env.development]
WORKING_DIR = { script = ["pwd"] }
RUST_BACKTRACE = 1
RUST_LOG = "trace"

[tasks.setcap]
command = "sudo"
args = ["setcap", "cap_net_raw,cap_net_admin=eip", "${WORKING_DIR}/target/debug/pulso"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.test]
command = "cargo"
args = ["test", "${@}"]
dependencies = ["build", "setcap"]

[tasks.run]
command = "cargo"
args = ["run", "${@}"]
dependencies = ["build", "setcap"]
